# Generated by Django 3.0.5 on 2020-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam'), (2, 'Không xác định')], default=1),
        ),
    ]
