# Generated by Django 3.0.5 on 2020-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponDescription',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
