# Generated by Django 3.0.5 on 2020-04-22 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=128)),
                ('brandDesc', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=128)),
                ('categoryThumbnail', models.CharField(default='', max_length=255)),
                ('categoryDesc', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=64)),
                ('colorDesc', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(max_length=32, unique=True)),
                ('expirationDate', models.DateField(default=django.utils.timezone.now)),
                ('discountRate', models.IntegerField(default=0)),
                ('discountAmount', models.IntegerField(default=0)),
                ('couponDescription', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=40)),
                ('quantityAvailable', models.IntegerField(default=0)),
                ('oldPrice', models.IntegerField(default=0)),
                ('newPrice', models.IntegerField(default=0)),
                ('detailShoeDesc', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Color')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=128)),
                ('statusDesc', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeName', models.CharField(max_length=255)),
                ('shoeThumbnail', models.CharField(max_length=255)),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('quantitySold', models.IntegerField(default=0)),
                ('viewCount', models.IntegerField(default=0)),
                ('favouriteCount', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('shoeDesc', models.CharField(blank=True, default='', max_length=2048)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateField(default=django.utils.timezone.now)),
                ('dateDelivery', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.CharField(max_length=128)),
                ('receiverNumber', models.CharField(max_length=32)),
                ('receiverAddress', models.CharField(max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('totalPayment', models.IntegerField()),
                ('orderPackageNote', models.CharField(blank=True, default='', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('detailShoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DetailShoe')),
                ('orderPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderPackage')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=255)),
                ('imageDesc', models.CharField(blank=True, default='', max_length=64)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Shoe')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Shoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detailshoe',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Shoe'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOnCart', models.IntegerField(default=1)),
                ('detailShoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DetailShoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
