# Generated by Django 3.0.5 on 2020-04-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
