# Generated by Django 3.0.5 on 2020-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200424_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='detailShoe',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='detailShoe',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderPackage',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPackageStatus',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderPackage',
        ),
    ]
