# Generated by Django 3.0.5 on 2020-04-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200428_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
