# Generated by Django 3.0.5 on 2020-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageName',
        ),
        migrations.AddField(
            model_name='image',
            name='shoeImage',
            field=models.ImageField(blank=True, upload_to='shoe_images'),
        ),
    ]
