# Generated by Django 3.0.5 on 2020-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200501_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoeThumbnail',
            field=models.ImageField(blank=True, upload_to='shoe_thumbnails'),
        ),
    ]
