# Generated by Django 3.0.5 on 2020-05-13 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200513_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
