# Generated by Django 3.0.5 on 2020-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200513_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image_static',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
