# Generated by Django 3.0.5 on 2020-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_shoe_image_static'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Thương hiệu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Loại giày'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Màu sắc'},
        ),
        migrations.AlterModelOptions(
            name='detailshoe',
            options={'verbose_name_plural': 'Thông tin chi tiết giày'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'verbose_name_plural': 'Giày'},
        ),
        migrations.AlterField(
            model_name='shoe',
            name='active',
            field=models.IntegerField(choices=[(0, 'Không kinh doanh'), (1, 'Đang kinh doanh')], default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoeDesc',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='color',
            table='color',
        ),
        migrations.AlterModelTable(
            name='detailshoe',
            table='detail_shoe',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='shoe',
            table='shoe',
        ),
    ]
