# Generated by Django 3.0.5 on 2020-06-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200613_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='color',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detailshoe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shoe',
            table=None,
        ),
    ]
