# Generated by Django 3.0.5 on 2020-04-23 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=1024)),
                ('dateSend', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
