# Generated by Django 3.0.5 on 2020-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_feedback_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
