# Generated by Django 3.0.5 on 2020-04-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0002_auto_20200428_1642'),
        ('mainapp', '0004_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=128)),
                ('statusDesc', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateField(default=django.utils.timezone.now)),
                ('dateDelivery', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.CharField(max_length=128)),
                ('receiverNumber', models.CharField(max_length=32)),
                ('receiverAddress', models.CharField(max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('totalPayment', models.IntegerField()),
                ('orderPackageNote', models.CharField(blank=True, default='', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('detailShoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DetailShoe')),
                ('orderPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderPackage')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOnCart', models.IntegerField(default=1)),
                ('detailShoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DetailShoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
