# Generated by Django 3.0.5 on 2020-05-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='detailShoe',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderPackage',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPackageStatus',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderPackage',
        ),
    ]
