# Generated by Django 3.0.5 on 2020-06-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200613_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
