# Generated by Django 3.0.5 on 2020-05-03 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0006_auto_20200501_2306'),
        ('coupon', '0003_coupon_couponamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateField(default=django.utils.timezone.now)),
                ('dateDelivery', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.CharField(max_length=128)),
                ('receiverNumber', models.CharField(max_length=32)),
                ('receiverAddress', models.CharField(max_length=255)),
                ('note', models.TextField(default='', max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Đã hủy'), (1, 'Chờ xác nhận'), (2, 'Đang giao'), (3, 'Đã giao')])),
                ('totalPayment', models.IntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('detailShoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DetailShoe')),
                ('orderPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderPackage')),
            ],
        ),
    ]
