# Generated by Django 3.0.5 on 2020-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackage',
            name='note',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đã hủy (user)'), (1, 'Chờ xác nhận'), (2, 'Đang giao'), (3, 'Đã giao'), (4, 'Từ chối (admin)')]),
        ),
    ]
