# Generated by Django 3.0.5 on 2020-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200513_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpackage',
            options={'ordering': ('status', 'user')},
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đang giao'), (3, 'Đã giao'), (4, 'Cửa hàng từ chối'), (5, 'Người dùng hủy')]),
        ),
    ]
