# Generated by Django 3.0.5 on 2020-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200520_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpackage',
            options={'ordering': ('status', '-id'), 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='orderpackage',
            table='order_package',
        ),
    ]
