# Generated by Django 3.0.5 on 2020-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='date_like',
            field=models.DateField(auto_now=True),
        ),
    ]
