# Generated by Django 3.0.5 on 2020-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_favourite_date_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favourite',
            table='favourite',
        ),
    ]
